steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    
  # Run tests (optional - uncomment if you have tests)
  # - name: 'node:18'
  #   entrypoint: npm
  #   args: ['test']
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

# Specify the timeout for the build
timeout: '1200s'

# Options for the build
options:
  logging: CLOUD_LOGGING_ONLY